### ISSUE TITLE
Can't resolve 'draft-js' (after performing the installation steps)

### ISSUE THREAD

**Issue by nitayneeman** [wix-incubator/rich-content#265]
I'm wondering if the library depends on `@wix/draft-js` and `draft-js` either, because I'm faced with an error after performing the installation steps mentioned in the guide.

The error is:
```
ERROR in ./node_modules/wix-rich-content-editor/dist/module.cjs.js
Module not found: Error: Can't resolve 'draft-js/lib/DraftOffsetKey' in '{PROJECT-PATH}/node_modules/wix-rich-content-editor/dist'
 @ ./node_modules/wix-rich-content-editor/dist/module.cjs.js 1:922-960
```

👉 The question - is there any prerequisite for installing `draft-js` also (besides `@wix/draft-js`)?

The steps were performed:
1. Creating a completely new application using Yoshi
2. Installing `wix-rich-content-editor` and `wix-rich-content-viewer`
3. Installing `@wix/draft-js`
4. Using the component exactly as the code example (with the `render`) demonstrates
5. npm start
6. Getting the error above

Note: Obviously it works as expected after installing `draft-js`.

**Comment by bchmn** [comment]
This happens since use some of the plugins from [draft-js-plugins](https://www.draft-js-plugins.com/) under the hood and they reference `draft-js`.
We solved this in our [examples](https://github.com/wix-incubator/rich-content/blob/master/examples/editor/config/webpack.common.js#L23) using webpacks `resolve.alias` functionality.
Yoshi also supports [resolve.alias](https://wix.github.io/yoshi/docs/api/configuration#resolvealias).

**Comment by nitayneeman** [comment]
Thanks!
